name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-dep-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
          name: Setup Yarn dep cache
          id: yarn-dep-cache
          with:
            path: ${{ steps.yarn-dep-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-dep-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
            ${{ runner.os }}-yarn-dep-
      - name: Yarn install deps
          run: |
              yarn install --frozen-lockfile
          if: steps.yarn-dep-cache.outputs.cache-hit != 'true'

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v1
          name: Setup Yarn build cache
          id: yarn-build-cache
          with:
            path: frontend/dist
            key: ${{ runner.os }}-yarn-build-$  {{ hashFiles('frontend/src/') }}
            restore-keys: |
                ${{ runner.os }}-yarn-build-
      - name: Yarn build
        run: |
            yarn build
        if: steps.yarn-build-cache.outputs.cache-hit != 'true'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          browser: chrome
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
