name: E2E Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run cypress tests
      - name: Run Cypress
        uses: cypress-io/github-action@v4.1.0
        with:
          working-directory: ui
          install-command: yarn install
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
      # Save screenshots on fail
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          working-directory: ui
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          working-directory: ui
          name: cypress-videos
          path: cypress/videos
